export const MONTHS = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre",
];
export const WDAYS = ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"];
export const STORAGE_KEY = "hospital_schedule_v1";

export const TURN_LABEL = { TM: "M", TT: "T", TN: "N" };

export const CELL_TYPES = {
  TM: { label: "M", bg: "#fff", fg: "#1d4ed8", hours: 7 },
  TT: { label: "T", bg: "#fff", fg: "#15803d", hours: 7 },
  TN: { label: "N", bg: "#fff", fg: "#000", hours: 10 },
  F: { label: "F", bg: "#fff", fg: "#374151", hours: 0 },
  FE: { label: "F°", bg: "#fff", fg: "#dc2626", hours: 0 },
  LIC: { label: "Lic", bg: "#fef9c3", fg: "#7c2d12", hours: 0 },
  EARLY: { label: "●", bg: "#fce7f3", fg: "#9d174d", hours: 0 },
  LATE: { label: "●", bg: "#dcfce7", fg: "#166534", hours: 0 },
  LAR: { label: "LAR", bg: "#fef3c7", fg: "#92400e", hours: 0 },
  PM: { label: "PM", bg: "#dbeafe", fg: "#1e3a8a", hours: 0 },
  "---": { label: "", bg: "#fff", fg: "#94a3b8", hours: 0 },
};

export const REGIMES = {
  R15: { label: "Régimen 15", hours: 160 },
  R27: { label: "Régimen 27", hours: 144 },
  H24: { label: "24hs Semanal", hours: 88 },
};

export const INITIAL_EMPLOYEES = [
  {
    id: 1,
    name: "Spinoza Claudia",
    regime: "R27",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 2,
    name: "Nuñez Celestina",
    regime: "R27",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 3,
    name: "Ajaya Veronica",
    regime: "R27",
    turn: "TM",
    reduction: 25,
    note: "Red.25%",
  },
  {
    id: 4,
    name: "Lazzaro Claudia",
    regime: "R27",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 5,
    name: "Morganti Gisela",
    regime: "R27",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 6,
    name: "Quiroga Jesica",
    regime: "R27",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 7,
    name: "Marino Laura",
    regime: "R27",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 8,
    name: "Martinez Yenny",
    regime: "R15",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 9,
    name: "Quezada Daiana",
    regime: "R15",
    turn: "TM",
    reduction: 0,
    note: "Ingr.09/25",
  },
  {
    id: 10,
    name: "Dominguez Yamila",
    regime: "R15",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 11,
    name: "Venturini Geraldine",
    regime: "R15",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 12,
    name: "Pereira Gisel",
    regime: "R15",
    turn: "TM",
    reduction: 0,
    note: "",
  },
  {
    id: 13,
    name: "Abarza Alejandra",
    regime: "R27",
    turn: "TT",
    reduction: 0,
    note: "",
  },
  {
    id: 14,
    name: "Nievas Eliana",
    regime: "R27",
    turn: "TT",
    reduction: 0,
    note: "",
  },
  {
    id: 15,
    name: "Peña Janet",
    regime: "R27",
    turn: "TT",
    reduction: 0,
    note: "",
  },
  {
    id: 16,
    name: "Aguirre Tamara",
    regime: "R15",
    turn: "TT",
    reduction: 0,
    note: "Ingr.06/25",
  },
  {
    id: 17,
    name: "Mardones Claudia",
    regime: "R15",
    turn: "TT",
    reduction: 0,
    note: "",
  },
  {
    id: 18,
    name: "Condori Joana",
    regime: "R27",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 19,
    name: "Bullones Priscila",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 20,
    name: "Garcia Laura",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 21,
    name: "Castilo Natalia",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 22,
    name: "Aguirre Mirian",
    regime: "H24",
    turn: "TN",
    reduction: 0,
    note: "24hs",
  },
  {
    id: 23,
    name: "Gomez Betiana",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 24,
    name: "Quispe Andrea",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 25,
    name: "Diaz Eliana",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 26,
    name: "Olmedo Melisa",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 27,
    name: "Bustos Elizabeth",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 28,
    name: "Perez Sabrina",
    regime: "R15",
    turn: "TN",
    reduction: 0,
    note: "",
  },
  {
    id: 29,
    name: "Siles Liliana",
    regime: "R27",
    turn: "TN",
    reduction: 0,
    note: "Part.med.",
  },
];

export const MAX_CONSECUTIVE = { TM: 4, TT: 4, TN: 2 };
export const MAX_CONSEC_FRANCO = 3;
