export const S = {
  app: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "#fff",
    color: "#1e293b",
  },
  hdr: {
    background: "#1e40af",
    borderBottom: "2px solid #1e3a8a",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
  },
  hdrTitle: {
    fontFamily: "'Barlow Condensed',sans-serif",
    fontSize: 26,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: 1,
    lineHeight: 1,
  },
  hdrSub: { fontSize: 11, color: "#bfdbfe", fontWeight: 600, marginTop: 2 },
  monthNav: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  navBtn: {
    background: "rgba(255,255,255,0.15)",
    border: "1px solid rgba(255,255,255,0.3)",
    color: "#fff",
    padding: "6px 14px",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 14,
  },
  monthLbl: {
    fontFamily: "'Barlow Condensed',sans-serif",
    fontSize: 22,
    fontWeight: 700,
    color: "#fff",
    minWidth: 200,
    textAlign: "center",
    letterSpacing: 1,
  },
  tabs: {
    display: "flex",
    gap: 1,
    padding: "10px 20px 0",
    background: "#fff",
    borderBottom: "2px solid #e2e8f0",
  },
  content: { flex: 1, padding: "14px 20px", background: "#fff" },
  gridWrap: { overflowX: "auto", border: "1px solid #000" },
  thName: {
    background: "#fff",
    color: "#1e293b",
    padding: "7px 10px",
    minWidth: 175,
    position: "sticky",
    left: 0,
    zIndex: 12,
    fontSize: 11,
    fontWeight: 700,
    textAlign: "left",
    whiteSpace: "nowrap",
    border: "1px solid #cbd5e1",
  },
  thMeta: {
    background: "#fff",
    color: "#374151",
    padding: "5px 6px",
    textAlign: "center",
    fontSize: 10,
    whiteSpace: "nowrap",
    minWidth: 52,
    border: "1px solid #cbd5e1",
  },
  tdName: {
    background: "#fff",
    color: "#1e293b",
    padding: "5px 10px",
    position: "sticky",
    left: 0,
    zIndex: 5,
    fontSize: 11,
    whiteSpace: "nowrap",
    border: "1px solid #e2e8f0",
  },
  tdMeta: {
    background: "#fff",
    padding: "4px 5px",
    textAlign: "center",
    fontSize: 11,
    fontWeight: 600,
    border: "1px solid #cbd5e1",
  },
  cell: {
    width: 30,
    height: 26,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Barlow Condensed',sans-serif",
    fontWeight: 700,
    fontSize: 10,
    userSelect: "none",
  },
  btn: (bg, fg = "#fff") => ({
    padding: "6px 14px",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 700,
    background: bg,
    color: fg,
    letterSpacing: ".5px",
  }),
  formInput: {
    background: "#fff",
    border: "1px solid #cbd5e1",
    color: "#1e293b",
    padding: "5px 10px",
    borderRadius: 6,
    fontSize: 12,
    outline: "none",
  },
  formSel: {
    background: "#fff",
    border: "1px solid #cbd5e1",
    color: "#1e293b",
    padding: "5px 10px",
    borderRadius: 6,
    fontSize: 12,
    cursor: "pointer",
  },
  formLabel: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: 700,
    letterSpacing: ".5px",
    marginBottom: 3,
    display: "block",
  },
  cfgBox: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  cfgTitle: {
    fontFamily: "'Barlow Condensed',sans-serif",
    fontSize: 15,
    fontWeight: 700,
    color: "#1e40af",
    marginBottom: 10,
    letterSpacing: 1,
  },
};
